name: Power On Droplet

on:
  schedule:
    - cron: '0 8 * * *'   # هذا الوقت UTC
  workflow_dispatch:

jobs:
  power-on:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Power On Droplet
        run: doctl compute droplet-action power-on ${{ secrets.DROPLET_ID }}
